In [1]:
import scipy.io as io
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
data = io.loadmat("WLDataCW.mat")

In [3]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Fri Jan 21 21:10:34 2022',
 '__version__': '1.0',
 '__globals__': [],
 'data': array([[[ 3.64516091e+00, -1.22507811e+00,  8.41415691e+00, ...,
          -1.16731644e+01,  2.65084229e+01,  4.00945067e-01],
         [ 1.57700694e+00,  2.68786597e+00,  2.37991428e+00, ...,
          -9.80385399e+00,  2.95700607e+01,  1.86778176e+00],
         [-2.88467383e+00,  3.47892046e+00, -3.33852053e+00, ...,
          -7.33824921e+00,  3.09278240e+01,  2.78261375e+00],
         ...,
         [ 6.32441854e+00,  7.38758564e+00, -5.30264425e+00, ...,
           2.92871971e+01, -2.80428171e-01, -4.32558784e+01],
         [-5.14494121e-01,  1.25400152e+01, -2.38987041e+00, ...,
           2.50036125e+01, -1.41281223e+00, -3.64643059e+01],
         [-3.36245584e+00,  1.25796471e+01,  1.27706754e+00, ...,
           2.42137814e+01, -1.03876221e+00, -3.15475597e+01]],
 
        [[ 1.40172338e+01,  6.67675018e+00,  1.04504976e+01, ...,
   

In [4]:

X = data['data']

In [5]:
X

array([[[ 3.64516091e+00, -1.22507811e+00,  8.41415691e+00, ...,
         -1.16731644e+01,  2.65084229e+01,  4.00945067e-01],
        [ 1.57700694e+00,  2.68786597e+00,  2.37991428e+00, ...,
         -9.80385399e+00,  2.95700607e+01,  1.86778176e+00],
        [-2.88467383e+00,  3.47892046e+00, -3.33852053e+00, ...,
         -7.33824921e+00,  3.09278240e+01,  2.78261375e+00],
        ...,
        [ 6.32441854e+00,  7.38758564e+00, -5.30264425e+00, ...,
          2.92871971e+01, -2.80428171e-01, -4.32558784e+01],
        [-5.14494121e-01,  1.25400152e+01, -2.38987041e+00, ...,
          2.50036125e+01, -1.41281223e+00, -3.64643059e+01],
        [-3.36245584e+00,  1.25796471e+01,  1.27706754e+00, ...,
          2.42137814e+01, -1.03876221e+00, -3.15475597e+01]],

       [[ 1.40172338e+01,  6.67675018e+00,  1.04504976e+01, ...,
         -7.23842859e+00,  2.92477169e+01, -6.11521196e+00],
        [ 9.57320786e+00,  1.03044224e+01,  4.34053040e+00, ...,
         -4.79710388e+00,  3.15305920e

In [6]:
X = X.reshape((X.shape[0]*X.shape[1]), X.shape[2]).T


In [7]:
X.shape

(360, 31744)

In [8]:
X

array([[  3.645161  ,   1.5770069 ,  -2.8846738 , ...,   6.510839  ,
         12.609276  ,  17.854654  ],
       [ -1.2250781 ,   2.687866  ,   3.4789205 , ..., -26.119247  ,
        -26.75478   , -22.282345  ],
       [  8.414157  ,   2.3799143 ,  -3.3385205 , ..., -18.81463   ,
        -20.730404  , -11.228072  ],
       ...,
       [-11.673164  ,  -9.803854  ,  -7.338249  , ...,   7.9561925 ,
          7.9090223 ,   7.063335  ],
       [ 26.508423  ,  29.57006   ,  30.927824  , ...,  -0.68776023,
         -1.1107184 ,  -1.096807  ],
       [  0.40094507,   1.8677818 ,   2.7826138 , ..., -50.413074  ,
        -67.15403   , -66.17021   ]], dtype=float32)

In [9]:
y = data['label']

In [10]:
y.shape

(1, 360)

In [11]:
y= y.T

In [12]:
y.shape

(360, 1)

In [13]:
y = pd.DataFrame(y)

In [14]:
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
355  1
356  1
357  1
358  1
359  1

[360 rows x 1 columns]

In [15]:
len(X)

360

In [16]:
len(y)

360

In [17]:
# def standardize(X):
#     X = np.transpose(X)
#     for i in range(X.shape[1]):
#         X = (X - X.mean(axis=0))/X.std(axis=0)
#     return np.transpose(X)

In [18]:
scaler=StandardScaler()
X_transform = scaler.fit_transform(X)

In [19]:
 X_train, X_test, y_train, y_test = train_test_split(X_transform, y, test_size=0.2, random_state=42)

In [20]:
X_train.shape

(288, 31744)

In [21]:
def initialize(X):
    w = np.zeros((np.shape(X_train)[1],1))
    #b = np.c_[np.zeros((np.shape(X_train)[0])),X_train]
    return w,0

In [22]:
w,b = initialize(X)

In [23]:
w

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [24]:
w.shape

(31744, 1)

In [25]:
b

0

In [26]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [27]:
 def cross_entropy(y,y_hat,k):
        loss=(-np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat)))/k
        return loss

In [28]:
    def partial_der_weight_bias(k, x, y_hat, y):   
        dL_dW = np.dot(x.T, (y_hat -y)) * 0.01 / k    
        dL_db = (y_hat - y )* 0.01 / k
        return  dL_dW,dL_db 

In [29]:
def predict(X):

    preds = sigmoid(np.dot(X, w) + b)
    pred_class = []
    pred_class = [1 if i > 0.5 else 0 for i in preds]
    
    return np.array(pred_class)

In [30]:
  
def accuracy(y, y_hat):
    accuracy = np.sum(y == y_hat) / len(y)
    return accuracy

In [31]:
def logisticModel(X, y, learning_rate):
    
    k = X.shape[0]
    weights,bias = initialize(X)
    y_hat = sigmoid((np.dot(np.transpose(w), X) + b))
    dw, db = partial_der_weight_bias(k,X_train,y_hat.T,y_train)
    weights = w - dw.T
    bias = b - db.T
    loss = cross_entropy(y,y_hat.T,k)
    
    return w,b,loss
    
    
    
    
    


In [32]:
w.shape

(31744, 1)

In [33]:
weights,bias,loss = logisticModel(X_train.T,y_train,0.01)

In [34]:
loss

0    0.006289
dtype: float64

In [35]:
y_pred= predict(X_test)

In [36]:
 y_pred = y_pred.reshape(y_pred.shape[0], 1)

In [37]:
acc = accuracy(y_test,y_pred)

In [38]:
 print('Accuracy: ', acc[0])

Accuracy:  0.5138888888888888


In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.51      1.00      0.68        37
           1       0.00      0.00      0.00        35

    accuracy                           0.51        72
   macro avg       0.26      0.50      0.34        72
weighted avg       0.26      0.51      0.35        72



C:\Users\Dell\miniconda3\envs\ce802\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
